version: '3'

tasks:
  build:
    cmds:
      - go build -o ./build/redis-internals main.go
    desc: Build the application

  test:
    cmds:
      - mockery && go test ./...
    desc: Run tests

  clean:
    cmds:
      - rm -f ./build/redis-internals
    desc: Clean the build artifacts

  brun:
    cmds:
      - task: build
      - ./build/redis-internals
    desc: Build and run the application

  run:
    cmds:
      - go run main.go